symbol: BTCUSDT
interval: 15m           # ✅ GANTI dari '5m' ke '15m'
window_size: 50

threshold: 0.0003       # atau bisa coba 0.0004 untuk 15m
tp_pct: 0.002           # 0.2%
sl_pct: 0.001           # 0.1%
margin_pct: 0.025       # 2.5%
leverage: 20
model_path: model_scalping_15m.pkl